### ISSUE TITLE
Should you have to explicitly import the route helpers?

### ISSUE THREAD

**Issue by marshallswain** [canjs/can-route#15]
I noticed that the routeUrl helper wouldn't work until I explicitly added it to my Can3 project:

```html
<can-import from="can-stache/helpers/route" />
<a href="{{routeUrl(app='dashboard' page='accounts')}}">Accounts</a>
```

Is this the expected usage?  If so, I'll document it.

**Comment by justinbmeyer** [comment]
Yeah, it's expected
