### ISSUE TITLE
Updating data in canRoute should not removed any properties on target that are not available on source

### ISSUE THREAD

**Issue by mjstahl** [canjs/can-route#160]
In a donejs application is you have an `app.js` file that looks like:
```js
import DefineMap from 'can-define/map/';
import route from 'can-route';
import 'can-route-pushstate';
import 'can-stache-bindings';

const ApplicationVM = DefineMap.extend({
  page: {
    type: 'string',
    get(currentPage) {
      return (this.session) ? (currentPage || 'foo') : 'login';
    },
    serialize: true
  },
  session: {
    type: 'any',
  },
});

route.register('{page}');
export default ApplicationVM;
```

In the console, run `can.viewModel('html').session = {}`. The expectation is that `page` would then be equal to `foo`.

It does not, because https://github.com/canjs/can-route/blob/master/can-route.js#L94 is calling `canReflect.update` where I think it should be calling `canReflect.assign`.

**Comment by justinbmeyer** [comment]
Needs to call update. I think session should be serialize: false

**Comment by justinbmeyer** [comment]
Needs to call update because if stateful properties in the url are removed when the url changes, they need to be removed from the view model.

**Comment by mjstahl** [comment]
Got it. That worked.

So what I think is a little wonky about this is:

1. I don't get route properties displayed in the route unless I `serialize: true`
2. Properties not on the route, but in the object need to be `serialize: false` otherwise they get deleted.

I think we should pick on and opt in. And in this case, I think that I am specifying a property in `route.register` (like `route.register('{page}');`) - `page` should be displayed in the route without `serialize: true`.

**Comment by justinbmeyer** [comment]
You can use 

“*”: {serialize: false} 

To change the defaults. 

I like the idea of making props identified by register as serialize:true no matter what. 

I’m not sure what to do about point number 2. How should we know which props are part of the url and which aren’t if we support urls like /foo/bar?zed=ted ?

**Comment by justinbmeyer** [comment]
We could show to use serialize:false trick to teach people how to opt in.

**Comment by justinbmeyer** [comment]
Another way would be to mount to route data to a property within your app vm. This way everything on that will be serialize true. This might be a better idea.

**Comment by justinbmeyer** [comment]
closing for #170
