### ISSUE TITLE
Tests failing: define.types.string is not a function

### ISSUE THREAD

**Issue by chasenlehara** [canjs/can-route#164]
This is what’s causing https://github.com/canjs/can-route/issues/161 and https://github.com/canjs/can-route/issues/163

**Comment by chasenlehara** [comment]
This is actually an issue in can-define: https://github.com/canjs/can-define/blob/c47d3050c9a663b37ce8bec163ec3a2ee2c46ea4/can-define.js#L1182

`define.types.string` should be a function, not an object.

**Comment by justinbmeyer** [comment]
Issue moved to [canjs/can-define #330](https://github.com/canjs/can-define/issues/330) via [**ZenHub**](https://www.zenhub.com/)
