### ISSUE TITLE
Route templates should be consistent across projects. ~21

### ISSUE THREAD

**Issue by mjstahl** [canjs/can-route#18]
`can.route` URL templates differ from `can.fixtures`. I am not sure which syntax is superior, but it should be consistent across project with as little deviation as possible. And if there is deviation, we should be able to explain the use cases.

The question that prompted this issue:

> marshall [10:21 AM]  
> @here, how to you setup a fixture with a wildcard id in the URL? (edited)
> 
> [10:21]  
> fixture({url: "/v1/accounts/:id", method: "put"}, function(request, response){
>  response(request.data);
> });
> 
> [10:21]  
> That doesn’t seem to do the trick.
> 
> james [10:21 AM]  
> {id} iirc
> 
> marshall [10:23 AM]  
> Thanks @james.  That did the trick.  I was confusing it with the can-route syntax, I think.

**Comment by justinbmeyer** [comment]
Yeah, I'd actually prefer the `{something}` because it makes accounting for breaks other than `/` possible like `place-{place.id}-page`.
