### ISSUE TITLE
Parent node is null

### ISSUE THREAD

**Issue by cherifGsoul** [canjs/can-route#196]
This [pen](https://codepen.io/cherifGsoul/pen/EppvrG) reprduce the error for this issue.
Steps:
* Click ```Main menu```
* Click ```List```
* Click ```Previous``` button in the browser
* Click ```New```

You see error in the console ```Uncaught TypeError: Cannot read property 'nodeName' of null```

**Comment by justinbmeyer** [comment]
![image](https://user-images.githubusercontent.com/78602/43690440-aac07ad6-98cf-11e8-9f83-6bff49a2a711.png)

**Comment by justinbmeyer** [comment]
@cherifGsoul does this happen if you change from a nested switch to a nested if?

I bet it's a problem with switch.

**Comment by cherifGsoul** [comment]
Yeah I think is from the nested switch case!

**Comment by justinbmeyer** [comment]
This is a problem with `switch()`, moving to `can-stache`

**Comment by justinbmeyer** [comment]
Issue moved to [canjs/can-stache #576](https://github.com/canjs/can-stache/issues/576) via [**ZenHub**](https://www.zenhub.com/)
