### ISSUE TITLE
Calling attr with an object on can-route.data stringifies object

### ISSUE THREAD

**Issue by mikemitchel** [canjs/can-route#197]
`stringCoercingMapDecorator` checks if a property is serializable before serializing here:

https://github.com/canjs/can-route/blob/cdeb144c5dededaad488d64e2f75907624dd0f07/can-route.js#L356

...but if `attr` is called with an object, this will always be true and everything will be serialized.

Here is an example: http://jsbin.com/cabucog/1/edit?html,js,console,output

**Comment by phillipskevin** [comment]
closed by #198.
