### ISSUE TITLE
Properties with undefined value in can.route.attr(obj) are ignored instead of removed ~5

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-route#20]
From:

https://github.com/canjs/canjs/issues/2287.

Essentially doing:

```
can.route.attr({foo: undefined})
```

doesn't set `foo` to undefined.

This is probably a bug within `can-map`.  We should make sure that can-define/map's `.set` works the same way.

**Comment by dylanrtt** [comment]
>This is probably a bug within `can-map`. We should make sure that can-define/map's `.set` works the same way.

`can-map` calls `removeAttr()` for values that are `undefined`.

https://github.com/canjs/can-map/blob/master/can-map.js#L479

The problem with `can-route` is that `undefined` properties are removed from the object during stringification before being passed to the map. I can see in this repo that the underlying utility changed (can-util/assign vs can.extend), which may have fixed this.

**Comment by phillipskevin** [comment]
This is no longer an issue.

Using a route backed by a DefineMap:
```
route.attr({ foo: 'bar' })
route.attr('foo') // "bar"
vm.foo // "bar"
route.attr({ foo: undefined })
route.attr('foo') // undefined
vm.foo // undefined
```

Also works with a route backed by a can-map:
```
route.attr({ foo: 'bar' })
route.attr('foo') // "bar"
vm.attr('foo') // "bar"
route.attr({ foo: undefined })
route.attr('foo') // undefined
vm.attr('foo') // undefined
```

**Comment by justinbmeyer** [comment]
@phillipskevin just to make sure ...  what is the result of:

```
route.serialize().hasOwnProperty('foo')
```

A property can be set to undefined, but still be part of the object.

**Comment by phillipskevin** [comment]
Just to confirm, `foo` is no longer part of the route after `{ foo: undefined }` is passed to `route.attr`.
