### ISSUE TITLE
Incorrect route matching

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-route#202]
`.register("", {page: "home", foo: "bar"})`

Then setting the url to:

`#!&foo=bar`

The `page` is still `home`.  This seems wrong.  I expect `page` to be undefined or at least `""`.

This codepen shows the problem:

https://codepen.io/justinbmeyer/pen/LJbpWb

**Comment by phillipskevin** [comment]
Is this actually wrong?

`#!&foo=bar` is matching the default route, so it is adding in the defaults https://github.com/canjs/can-route/blob/645ddfe8897d89684b705bb969b8a98f778bc300/src/deparam.js#L120

**Comment by phillipskevin** [comment]
`/^($|&)/` is the RegExp that gets built for this route... which is matched by `&foo=bar`.
