### ISSUE TITLE
filter property should be predefined

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-route#208]
I thought that we were creating properties automatically that matched registered routes.  But for some reason the following doesn't work if setting route.data removed from:

```js
        route.data = new DefineMap({filter: undefined});
        route.register("{filter}");
        route.start();
        return route.data;
```

and changed to:

```js
        route.register("{filter}");
        route.start();
        return route.data;
```

Codepen where that line can be removed:

https://codepen.io/justinbmeyer/pen/KxYqLJ?editors=1111

Once `route.data = new DefineMap({filter: undefined});`, clicking the completed link does nothing.

**Comment by matthewp** [comment]
It doesn't do it if you provide your own route.data.

**Comment by matthewp** [comment]
I guess this is what you would change: https://github.com/canjs/can-route/blob/8335c250863725da060bbe7a104602b31fdf25ae/src/register.js#L101 . You'd want to look over the name and check if a key is already defined. Not sure if I see the value of this feature though. The idea of 4.4 was to remove the need to set route.data at all.

**Comment by justinbmeyer** [comment]
I believe it was not working when I used the default route.data. I think this is due to the issue I created in can-define last night.
