### ISSUE TITLE
Docco comments

### ISSUE THREAD

**Issue by HTMLGhozt** [canjs/can-route#221]
## can-route.js
- [x] Removed jshint -W079 as it not default, nor in the config.

## string-coercion.js
- [x] duplicated test in if statement
- [x] refactored ternary to if else for code clarity
- [x] clear variable names `sym` -> `decoratorSymbol`

## linting
- [x] prefer double quotes
- [x] prefer tabs
- [x] prefer function declarations

**Comment by cherifGsoul** [comment]
Fixed and released:
https://github.com/canjs/can-route/releases/tag/v4.4.8
