### ISSUE TITLE
Handle _blank being clicked on. ~5

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-route#23]
From: https://github.com/canjs/canjs/issues/2452

We should ignore href="_blank" and perhaps others like void and such.

**Comment by Macrofig** [comment]
@justinbmeyer I think this is more of a pushstate issue. I know for sure it needs fixing there. I reviewed the can-route code but I'm unsure if can-route needs an update. If it does, who can I pair with to help me review the code?

**Comment by matthewp** [comment]
Yeah, I don't think this is related to can-route, going to close for now.
