### ISSUE TITLE
route("/{page}", {page: "home"}) doesn't handle route like http://myapp.com

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-route#47]

**Comment by christopherjbaker** [comment]
It looks like any leading slashes from inputs [are trimed](https://github.com/canjs/can-route/blob/master/can-route.js#L494), so `http://example.com` and `http://example.com/` should receive the same treatment. It also looks like the route config paths [are also trimmed](https://github.com/canjs/can-route/blob/master/can-route.js#L145).

I also tested `route('/{page}', { page: 'home' });` in a demo app (place my order) and it matched my naked domain. If that doesn't address the issue, can you clarify or provide a test case?

**Comment by chasenlehara** [comment]
I think I’ve experienced this issue on a personal project so I may be able to help in reproducing it.

**Comment by justinbmeyer** [comment]
@christopherjbaker this happened with donejs-chat.

**Comment by chasenlehara** [comment]
@christopherjbaker, please confirm this issue with @justinbmeyer. I’ll file a separate issue for what I’ve experienced.

**Comment by justinbmeyer** [comment]
closing, we can't re-create
