### ISSUE TITLE
Route regex doesn't match query strings, creates redirection feedback

### ISSUE THREAD

**Issue by Bajix** [canjs/can-route#56]
```
var route = require('can-route');
route('search')
// route.routes.search.test = /^search($|&)/
// route.deparam('/search?q=can-route') = {/search?q: "can-route"}
```

The above generated regex pattern is incorrect, and should be `/^search($|&|?)/`.

This breaks routing when opening pages with queries by creating a feedback loop within route.setState, which is dependent on param/deparam idempotency.

**Comment by christopherjbaker** [comment]
The second part of the regex is dependent upon the expected querySeparator. The [default behaviour](https://github.com/canjs/can-route/blob/master/can-route.js#L773) expects an `&`, though `can-route-pushstate` [switches this](https://github.com/canjs/can-route-pushstate/blob/master/can-route-pushstate.js#L75) to a `?`.

When setState calls deparam, it does so with the current window.location, so even if it is happening recursively, it is using the same type of information, so should use the correct `&`/`?` as needed. As such, I cannot see the use case where these would not line up.

**Comment by justinbmeyer** [comment]
@Bajix yeah, let us know what you were intending with `route('search')`.  Otherwise, we'll close this.  Thanks!
