### ISSUE TITLE
Remove usage of can-util/js/deparam

### ISSUE THREAD

**Issue by matthewp** [canjs/can-route#69]
https://github.com/canjs/can-route/blob/7cff0561d8dbde9697911fd1d3512c98fb2a6a3a/can-route.js#L8

This should use can-deparam directly. This is causing warnings in users' applications that they cannot get rid of.

**Comment by matthewp** [comment]
We need this for can-param as well. I missed that. :(

**Comment by andrejewski** [comment]
I'm on it. I should have caught that as well

**Comment by matthewp** [comment]
np, thanks.

**Comment by andrejewski** [comment]
Fixed and will be published in next patch.

**Comment by matthewp** [comment]
it is in 3.0.10, thanks!
