### ISSUE TITLE
Expects route.data to have a serialize() method

### ISSUE THREAD

**Issue by matthewp** [canjs/can-route#75]
This is perhaps something can-reflect can fix? @justinbmeyer @bmomberger-bitovi 

https://github.com/canjs/can-route/blob/00b40181462a615098aef60f667a4a2c20714070/can-route.js#L890

**Comment by justinbmeyer** [comment]
Yeah, we mostly need to loop through all the keys

**Comment by matthewp** [comment]
can-reflect is used now.
