### ISSUE TITLE
Listening to changes in can-route doesn't work as documented

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-route#78]
Reported on [gitter](https://gitter.im/donejs/donejs?at=591da1e15e34568d5e68c02e)

The `Listening to changes in can-route` docs here: https://canjs.com/doc/can-route.html#data don't work as documented.

This is either a bug that should be fixed, or the documentation should be changed to show 

```
route.matched.on('change', function(ev, attr, how, newVal, oldVal) {
    
})
```

**Comment by justinbmeyer** [comment]
@phillipskevin 

We probably want to show listening to individual properties change like:

```js
route.on('page', function(ev, newVal, oldVal) {

});
```

Or we want to show when a collection of properties has changed.  I don't think `.matched` would offer this. It would only fire when the route changed right?

**Comment by tracer99** [comment]
Correct, it only fires when the route changes. It also fires on the initial route initialization. This was what we needed. I couldn't get individual route properties working.

**Comment by justinbmeyer** [comment]
To listen on any data change, you would do:

```js
canRoute.serializedCompute.on("change", function(){

})
```

This is gross, we should come up with something better.

**Comment by justinbmeyer** [comment]
Actually, as the route is throttled, the better way of doing it is on the `__url` event on the [internal events object](https://github.com/canjs/can-route/blob/master/can-route.js#L248).

```
canEvent.dispatch.call(eventsObject,"__url",[path, lastHash]);
```

We could expose this like:

```js
canRoute.on("url", function(){

});
```

Though I'd be wary of conflicts ... what if someone has a URL property?  Should we do it like __keys? 

I wish we had symbols like:


```js
canRoute.on(canRoute.url, function(){

});
```

`canRoute.url` could be "special"?

**Comment by andrejewski** [comment]
*whispers from the bikeshed* `canRoute.on('*', function () {})` or `canRoute.on('routechange', function() {})`

**Comment by justinbmeyer** [comment]
@andrejewski maybe `routechange` ... I sorta was thinking this should be an available property.  Ideally in a 4.0, we'd support `route.url` which would be an observable property so that the following would be identical to listening on __url:

```js
var routeValue = compute(function(){
  return route.url;
});

routeValue.on("change", function(){ ... })
```

It's kind of strange that route's `on`, `addEventListener`/etc is a thin wrapper over `route.data`.  Maybe in 4.0 we should remove that wrapper, make people go to `route.data` themselves.

**Comment by phillipskevin** [comment]
> Though I'd be wary of conflicts ... what if someone has a URL property?

Wouldn't that be `canRoute.data.url`?

**Comment by justinbmeyer** [comment]
@phillipskevin we don't add a `url` property to the data do we?  I thought we tried to remove everything like that.

**Comment by phillipskevin** [comment]
Right, we don't. What I'm getting at is... what did you mean by 
> Though I'd be wary of conflicts ... what if someone has a URL property?

**Comment by bmomberger-bitovi** [comment]
Closed via https://github.com/canjs/can-route/pull/80
