### ISSUE TITLE
Annoying "two routes with matching keys" warning

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-route#99]
This warning should not be displayed when the routes do not match, like in this case:
```
WARN: two routes were registered with matching keys:
	(1) route("internet", {"page":"internet"})
	(2) route("internet/", {"page":"internet"})
(1) will always be chosen since it was registered first
```

**Comment by phillipskevin** [comment]
Since these are different routes, the warning isn't wrong, but it is annoying. In the example above, if someone sets `page` to `"internet"` can-route will use route `(1)`. The user who created these routes should know this, but it is what they want, so a warning may not be necessary.

So, we either need a way to specify a route with an optional trailing `/` or a way to suppress this warning when we want to set up routes like this on purpose. Maybe we always suppress the warning if the only difference is the trailing slash?

**Comment by phillipskevin** [comment]
I think we should suppress this warning for routes that match aside for the trailing slash.

**Comment by bgando** [comment]
Warn for this:
```
(1) route("internet", {"page":"internet"})
(2) route("internet/", {"page":"website"})
```
But not this:
```
(1) route("internet", {"page":"internet"})
(2) route("internet/", {"page":"internet"})
```
